/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

/// <reference types="truffle-typings" />
import { BigNumber } from 'bignumber.js';

export interface MigrationsContract extends Truffle.Contract<MigrationsInstance> {
  'new'(meta?: Truffle.TransactionDetails): Promise<MigrationsInstance>;
}

export interface SMT256Contract extends Truffle.Contract<SMT256Instance> {
  'new'(meta?: Truffle.TransactionDetails): Promise<SMT256Instance>;
}

export interface SMT256RollUpContract extends Truffle.Contract<SMT256RollUpInstance> {
  'new'(meta?: Truffle.TransactionDetails): Promise<SMT256RollUpInstance>;
}

export interface MigrationsInstance extends Truffle.ContractInstance {
  last_completed_migration(txDetails?: Truffle.TransactionDetails): Promise<BigNumber>;

  owner(txDetails?: Truffle.TransactionDetails): Promise<string>;

  setCompleted: {
    (completed: number | BigNumber | string, txDetails?: Truffle.TransactionDetails): Promise<Truffle.TransactionResponse>;
    call(completed: number | BigNumber | string, txDetails?: Truffle.TransactionDetails): Promise<void>;
    sendTransaction(completed: number | BigNumber | string, txDetails?: Truffle.TransactionDetails): Promise<string>;
    estimateGas(completed: number | BigNumber | string, txDetails?: Truffle.TransactionDetails): Promise<number>;
  };

  upgrade: {
    (new_address: string | BigNumber, txDetails?: Truffle.TransactionDetails): Promise<Truffle.TransactionResponse>;
    call(new_address: string | BigNumber, txDetails?: Truffle.TransactionDetails): Promise<void>;
    sendTransaction(new_address: string | BigNumber, txDetails?: Truffle.TransactionDetails): Promise<string>;
    estimateGas(new_address: string | BigNumber, txDetails?: Truffle.TransactionDetails): Promise<number>;
  };
}

export interface SMT256Instance extends Truffle.ContractInstance {
  EXIST(txDetails?: Truffle.TransactionDetails): Promise<string>;

  NON_EXIST(txDetails?: Truffle.TransactionDetails): Promise<string>;

  inclusionProof(
    root: string | BigNumber,
    nullifier: string | BigNumber,
    siblings: (string | BigNumber)[],
    txDetails?: Truffle.TransactionDetails
  ): Promise<boolean>;

  nonInclusionProof(
    root: string | BigNumber,
    nullifier: string | BigNumber,
    siblings: (string | BigNumber)[],
    txDetails?: Truffle.TransactionDetails
  ): Promise<boolean>;

  merkleProof(
    root: string | BigNumber,
    leaf: string | BigNumber,
    value: string | BigNumber,
    siblings: (string | BigNumber)[],
    txDetails?: Truffle.TransactionDetails
  ): Promise<boolean>;

  rollUp1(
    root: string | BigNumber,
    nextRoot: string | BigNumber,
    nullifier: string | BigNumber,
    siblings: (string | BigNumber)[],
    txDetails?: Truffle.TransactionDetails
  ): Promise<string>;

  rollUp2(
    root: string | BigNumber,
    nextRoots: (string | BigNumber)[],
    nullifiers: (string | BigNumber)[],
    siblings: (string | BigNumber)[][],
    txDetails?: Truffle.TransactionDetails
  ): Promise<string>;

  rollUp4(
    root: string | BigNumber,
    nextRoots: (string | BigNumber)[],
    nullifiers: (string | BigNumber)[],
    siblings: (string | BigNumber)[][],
    txDetails?: Truffle.TransactionDetails
  ): Promise<string>;

  rollUp8(
    root: string | BigNumber,
    nextRoots: (string | BigNumber)[],
    nullifiers: (string | BigNumber)[],
    siblings: (string | BigNumber)[][],
    txDetails?: Truffle.TransactionDetails
  ): Promise<string>;

  rollUp16(
    root: string | BigNumber,
    nextRoots: (string | BigNumber)[],
    nullifiers: (string | BigNumber)[],
    siblings: (string | BigNumber)[][],
    txDetails?: Truffle.TransactionDetails
  ): Promise<string>;

  rollUp32(
    root: string | BigNumber,
    nextRoots: (string | BigNumber)[],
    nullifiers: (string | BigNumber)[],
    siblings: (string | BigNumber)[][],
    txDetails?: Truffle.TransactionDetails
  ): Promise<string>;

  rollUp64(
    root: string | BigNumber,
    nextRoots: (string | BigNumber)[],
    nullifiers: (string | BigNumber)[],
    siblings: (string | BigNumber)[][],
    txDetails?: Truffle.TransactionDetails
  ): Promise<string>;
}

export interface SMT256RollUpInstance extends Truffle.ContractInstance {
  rollUp: {
    (txDetails?: Truffle.TransactionDetails): Promise<Truffle.TransactionResponse>;
    call(txDetails?: Truffle.TransactionDetails): Promise<boolean>;
    sendTransaction(txDetails?: Truffle.TransactionDetails): Promise<string>;
    estimateGas(txDetails?: Truffle.TransactionDetails): Promise<number>;
  };
}
